# Generated by Django 5.2.4 on 2025-08-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_award_blogpost_contactmessage_cv_experience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='issuer',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='skill',
            name='proficiency',
            field=models.CharField(max_length=1000),
        ),
    ]
